#!/usr/bin/env bash 


####
# Decription: crate new create-react-app application together with dependencies
# install new create-react-app application
# install create-react-app
# install bootstrap
# install font-awesome
# install axios
# install notifications???


#configuration
APPS_DIR=~/www/tests/react
APP_NAME=first-app

# display help
Help(){
cat <<EOF
Usage: ${0##*/} [-h | -l libraryName | -d directory ]

    -h help
    -l projectName - specify project name
    -d specify parent project directory name

EOF
}

# parse script options
while getopts ":hl:d:" option; do
   case $option in
      h) # display Help
         Help "$0"
         exit;;
      l) # Enter application name
         APP_NAME=$OPTARG;;
      d) # Enter directory   
         APPS_DIR=$OPTARG;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done
shift "$((OPTIND-1))"   # Discard the options and sentinel --

APP_PATH="$APPS_DIR/$APP_NAME"


# some testing for existing directories

if [[ ! -d "$APPS_DIR" ]]
  then {
    echo "Directory $APPS_DIR does not exist." 
    exit 1;
  }
fi   

if [[ -d "$APP_PATH" ]]
  then {
    echo "There exists $APP_PATH already. Choose a different app name" 
    exit 2;
  }
fi 


# create basic app scafolding
cd "$APPS_DIR"
npx create-react-app "$APP_NAME"

cd "$APP_NAME"

# install react_bootstrap
npm install react-bootstrap bootstrap
  # 1. import bootstrap css in src/index.js
  # import 'bootstrap/dist/css/bootstrap.css';

# install font awesome
npm i --save @fortawesome/fontawesome-svg-core
npm install --save @fortawesome/free-solid-svg-icons
npm install --save @fortawesome/react-fontawesome

# install react axios
npm install react-axios

read -r -d '' <<TND
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import reportWebVitals from './reportWebVitals';
import 'bootstrap/dist/css/bootstrap.css'; // bootstrap.css file
import { library } from '@fortawesome/fontawesome-svg-core' // fontawesome-svg-core
import { faCheckSquare, faCoffee } from '@fortawesome/free-solid-svg-icons' // fontawesome solid icons
import './index.css'; // index.css
library.add(faCheckSquare, faCoffee) // initialize fontawesome 

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
TND

echo "$REPLY" > src/index.js

read -r -d '' <<TND
import './App.css';
// import fontawesome icon 
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

// bootstrap elements
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

function App() {
  return (
    <div className="App">
      <h1>Welcome</h1>
    </div>
  );
}

export default App;
TND

echo "$REPLY" > src/App.js

# start development server
npm start
